Repository fabricjs/fabric.js, pull requests merged in 2022-04, with the labels that each got.

#7837 fix(itext): `set` during text editing
  src/mixins/itext_behavior.mixin.js
  src/shapes/itext.class.js
  test/unit/itext.js
Labels: itext

#7784 fix(itext): stop cursor on blur
  src/canvas.class.js
  src/mixins/itext_behavior.mixin.js
  src/mixins/itext_key_behavior.mixin.js
Labels: itext

#7775 fix(Canvas): safeguard dispose
  src/static_canvas.class.js
  test/unit/canvas.js
Labels: fix-next

#7674 fix(fabric.Text): support text alignments in RTL text
  src/mixins/itext.svg_export.js
  src/mixins/itext_click_behavior.mixin.js
  src/shapes/itext.class.js
  src/shapes/text.class.js
Labels: itext

#7857 chore(): PR template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: CI/CD

#7675 perf(SprayBrush): enhance perf using new Group
  src/brushes/spray_brush.class.js
Labels: feature

#7885 fix(Canvas): `dispose` race condition
  src/canvas.class.js
  test/unit/canvas.js
Labels: fix-next

#7906 refactor() change common ancenstors returned data to help isInFrontOf
  src/mixins/object_ancestry.mixin.js
  src/mixins/object_stacking.mixin.js
  test/unit/object.js
Labels: group, v6

#7875 chore(ci): rename option
  scripts/index.js
Labels: CI/CD

#7859 feat(Group): 2nd Patch of New Group! 🎉
  src/brushes/spray_brush.class.js
  src/canvas.class.js
  src/mixins/animation.mixin.js
  src/mixins/canvas_events.mixin.js
  src/mixins/canvas_grouping.mixin.js
  src/mixins/collection.mixin.js
  src/mixins/eraser_brush.mixin.js
  src/mixins/itext_behavior.mixin.js
  src/mixins/itext_click_behavior.mixin.js
  src/mixins/object_ancestry.mixin.js
  src/mixins/object_geometry.mixin.js
  src/mixins/object_stacking.mixin.js
  src/shapes/active_selection.class.js
  src/shapes/group.class.js
  src/static_canvas.class.js
  src/util/misc.js
  test/unit/collection.js
  test/unit/group.js
  test/unit/itext_click_behaviour.js
  test/unit/object.js
  test/visual/group_layout.js
Labels: group

#7915 ci(): fix build script option `exclude`
  scripts/index.js
Labels: CI/CD

#7907 fix(canvas export): regression caused by safegurading
  src/shapes/object.class.js
  test/unit/object.js
Labels: fix-next
