Repository fabricjs/fabric.js, pull requests merged in 2022-12, with the labels that each got.

#8482 chore(): refactor `Object.__uid++` => `uid()`
  CHANGELOG.md
  src/gradient/gradient.class.ts
  src/mixins/eraser_brush.mixin.ts
  src/mixins/object.svg_export.ts
  src/parser/parseSVGDocument.ts
  src/pattern.class.ts
  src/shadow.class.ts
  src/shapes/image.class.ts
  src/shapes/object.class.ts
  src/static_canvas.class.ts
  src/util/internals/uid.ts
  test/lib/assert.js
  test/node_test_setup.js
  test/testem.config.js
  test/unit/canvas.js
  test/unit/canvas_static.js
  test/unit/ellipse.js
  test/unit/gradient.js
  test/unit/group.js
  test/unit/image.js
  test/unit/path.js
  test/unit/pattern.js
  test/unit/shadow.js
  test/unit/text_to_svg.js
Labels: task

#8493 chore(TS): rm named_accessors
  CHANGELOG.md
  index.js
  src/util/named_accessors.mixin.ts
  test/unit/util.js
Labels: task

#8511 chore(TS): Move object classes
  CHANGELOG.md
  index.js
  src/EventTypeDefs.ts
  src/__types__.ts
  src/canvas.class.ts
  src/controls/control.class.ts
  src/controls/controls.render.ts
  src/controls/default_controls.ts
  src/controls/scale.ts
  src/controls/scaleSkew.ts
  src/controls/skew.ts
  src/controls/util.ts
  src/gradient/gradient.class.ts
  src/mixins/canvas_straightening.mixin.ts
  src/mixins/collection.mixin.ts
  src/mixins/itext.svg_export.ts
  src/mixins/object_stacking.mixin.ts
  src/mixins/text_style.mixin.ts
  src/parser/setStrokeFillOpacity.ts
  src/shadow.class.ts
  src/shapes/Object/AnimatableObject.ts
  src/shapes/Object/FabricObject.ts
  src/shapes/Object/InteractiveObject.ts
  src/shapes/Object/Object.ts
  src/shapes/Object/ObjectGeometry.ts
  src/shapes/Object/ObjectOrigin.ts
  src/shapes/Object/StackedObject.ts
  src/shapes/active_selection.class.ts
  src/shapes/circle.class.ts
  src/shapes/ellipse.class.ts
  src/shapes/group.class.ts
  src/shapes/image.class.ts
  src/shapes/itext.class.ts
  src/shapes/line.class.ts
  src/shapes/path.class.ts
  src/shapes/polygon.class.ts
  src/shapes/polyline.class.ts
  src/shapes/rect.class.ts
  src/shapes/text.class.ts
  src/shapes/textbox.class.ts
  src/shapes/triangle.class.ts
  src/static_canvas.class.ts
  src/util/misc/groupSVGElements.ts
  src/util/misc/mergeClipPaths.ts
  src/util/misc/objectEnlive.ts
  src/util/misc/objectTransforms.ts
  src/util/misc/planeChange.ts
  src/util/misc/resolveOrigin.ts
  src/util/types.ts
Labels: task

#8461 BREAKING(Object Stacking): 🔙 refactor logic to support Group 🔝
  CHANGELOG.md
  index.js
  src/canvas/static_canvas.class.ts
  src/mixins/collection.mixin.ts
  src/mixins/object_stacking.mixin.ts
  src/shapes/Object/ObjectGeometry.ts
  src/shapes/active_selection.class.ts
  src/shapes/group.class.ts
  test/unit/activeselection.js
  test/unit/canvas.js
  test/unit/canvas_static.js
  test/unit/group.js
  test/unit/object.js
Labels: group

#8297 chore(TS): animation
  CHANGELOG.md
  src/canvas/static_canvas.class.ts
  src/color/color.class.ts
  src/color/util.ts
  src/shapes/Object/AnimatableObject.ts
  src/shapes/Object/Object.ts
  src/util/animate.ts
  src/util/animate_color.ts
  src/util/animation/AnimationBase.ts
  src/util/animation/AnimationFrameProvider.ts
  src/util/animation/AnimationRegistry.ts
  src/util/animation/ArrayAnimation.ts
  src/util/animation/ColorAnimation.ts
  src/util/animation/ValueAnimation.ts
  src/util/animation/animate.ts
  src/util/animation/easing.ts
  src/util/animation/index.ts
  src/util/animation/types.ts
  src/util/animation_registry.ts
  src/util/misc/misc.ts
  test/ts/animation.ts
  test/unit/animation.js
  test/unit/canvas.js
  test/unit/canvas_static.js
  test/unit/color.js
  test/unit/object.js
Labels: v6
