Repository fabricjs/fabric.js, pull requests merged in 2022-06, with the labels that each got.

#7956 fix(): cleanup merge conflict resolution artifact
  src/canvas.class.js
Labels: task, v6

#7842 feat(Text): condensed styles structure
  src/mixins/itext.svg_export.js
  src/shapes/itext.class.js
  src/shapes/text.class.js
  src/shapes/textbox.class.js
  src/util/misc.js
  test/unit/itext.js
  test/unit/text.js
  test/unit/textbox.js
Labels: itext

#7515 fix(Canvas): flipped viewport transform coords
  src/static_canvas.class.js
  test/unit/canvas_static.js
  test/unit/object_geometry.js
Labels: feature, fix-next

#8000 fix(Group): patch #7916
  src/shapes/group.class.js
  src/static_canvas.class.js
  test/unit/group.js
  test/unit/object.js
Labels: group, v6

#7932 refactor(object_interactivity): draw borders
  src/mixins/object_interactivity.mixin.js
  src/shapes/object.class.js
  src/util/misc.js
Labels: v6

#8011 fix(canvas_events): `mouseout` bug
  src/mixins/canvas_events.mixin.js
  test/unit/canvas_events.js
Labels: bug

#8020 ci(typescript): transformer
  scripts/index.js
  scripts/transform_files.js
  src/mixins/canvas_gestures.mixin.js
  src/shapes/image.class.js
Labels: task, v6

#7827 feat(): support aborting promises/requests
  .eslintrc.json
  .github/workflows/node-unit-tests.yml
  .github/workflows/visual-node.yml
  src/filters/blendimage_filter.class.js
  src/filters/composed_filter.class.js
  src/mixins/canvas_serialization.mixin.js
  src/parser.js
  src/pattern.class.js
  src/shapes/image.class.js
  src/shapes/itext.class.js
  src/shapes/line.class.js
  src/shapes/object.class.js
  src/shapes/path.class.js
  src/shapes/polygon.class.js
  src/shapes/polyline.class.js
  src/shapes/text.class.js
  src/shapes/textbox.class.js
  src/util/dom_request.js
  src/util/misc.js
  test/unit/canvas_static.js
  test/unit/util.js
Labels: feature
