Repository fabricjs/fabric.js, pull requests merged in 2022-10, with the labels that each got.

#8357 fix(textStyles): Handle empty style object in stylesToArray
  CHANGELOG.md
  src/util/misc/textStyles.ts
  test/unit/text.js
Labels: fix-next

#8189 docs(): update guides
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/npmpublish.yml
  .gitignore
  .prettierignore
  .vscode/settings.json
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
Labels: docs

#8379 ci(): guides follow up
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/npmpublish.yml
  CHANGELOG.md
  CONTRIBUTING.md
Labels: docs, CI/CD

#8395 ci(): bundle size report
  .github/workflows/build.yml
  CHANGELOG.md
  package-lock.json
  package.json
  rollup.config.js
  rollup.test.config.js
  scripts/build.mjs
  scripts/buildStats.mjs
  scripts/index.mjs
  src/constants.ts
Labels: CI/CD

#8380 fix(): skewing controls
  CHANGELOG.md
  scripts/buildStats.mjs
  src/canvas.class.ts
  src/controls/controls.actions.ts
  src/typedefs.ts
  src/util/misc/matrix.ts
  test/unit/controls_handlers.js
Labels: fix-next

#8346 ci(): changelog action + merge directive
  .gitattributes
  .github/workflows/build.yml
  CHANGELOG.md
Labels: CI/CD
