Repository fabricjs/fabric.js, pull requests merged in 2022-08, with the labels that each got.

#8152 docs(Collection): JSDOC fix `item` return type
  src/mixins/collection.mixin.ts
Labels: docs

#8156 fix(): add pointer data to drop event
  src/mixins/canvas_events.mixin.ts
Labels: fix-next

#8138 ci(test): migrate test cmd
  .github/workflows/browser-chrome.yml
  .github/workflows/browser-firefox.yml
  .github/workflows/node-unit-tests.yml
  .github/workflows/visual-node.yml
  .github/workflows/visual-test-chrome.yml
  .github/workflows/visual-test-firefox.yml
  .gitignore
  old-travis-reference.yml
  package-lock.json
  package.json
  rollup.config.js
  rollup.test.config.js
  scripts/index.js
  test/GoldensServer.js
  test/lib/goldenMaker.html
  test/lib/tests.css
  test/lib/visualCallbackQunit.js
  test/lib/visualTestLoop.js
  test/node_test_setup.js
  test/testem.config.js
  test/testem.unit.js
  test/testem.visual.js
  test/tests.mustache
  test/unit/index.ts
  test/visual/index.ts
  testem-visual.json
  testem.json
  tests.mustache
Labels: CI/CD

#8179 fix(IText): regain focus on mouse move
  src/mixins/canvas_events.mixin.ts
  src/mixins/itext_behavior.mixin.ts
Labels: itext

#8187 fix(ci): inform ci of test failure
  scripts/index.js
Labels: CI/CD

#8205 ci(): update code coverage action comment
  .github/workflows/browser-chrome.yml
  .github/workflows/browser-firefox.yml
  .github/workflows/build.yml
  .github/workflows/node-unit-tests.yml
  package.json
Labels: CI/CD

#8188 fix(ci): report build script failure + revert node test runner to QUnit
  package.json
  scripts/index.js
  test/node_test_setup.js
  test/tests.mustache
Labels: CI/CD
