Repository fabricjs/fabric.js, pull requests merged in 2023-09, with the labels that each got.

#9192 fix(Textbox) Textbox inputs with new lines
  CHANGELOG.md
  e2e/tests/text/adding-text/index.spec.ts
  e2e/tests/text/adding-text/index.spec.ts-snapshots/1-initial-splitByGrapheme-false.png
  e2e/tests/text/adding-text/index.spec.ts-snapshots/1-initial-splitByGrapheme-true.png
  e2e/tests/text/adding-text/index.spec.ts-snapshots/2-before-pasting-splitByGrapheme-false.png
  e2e/tests/text/adding-text/index.spec.ts-snapshots/2-before-pasting-splitByGrapheme-true.png
  e2e/tests/text/adding-text/index.spec.ts-snapshots/3-after-pasting-splitByGrapheme-false.png
  e2e/tests/text/adding-text/index.spec.ts-snapshots/3-after-pasting-splitByGrapheme-true.png
  e2e/tests/text/adding-text/index.spec.ts-snapshots/4-after-adding-more-lines-splitByGrapheme-false.png
  e2e/tests/text/adding-text/index.spec.ts-snapshots/4-after-adding-more-lines-splitByGrapheme-true.png
  e2e/tests/text/adding-text/index.ts
  e2e/utils/CanvasUtil.ts
  src/shapes/Textbox.ts
Labels: bug, text

#9322 fix(ActiveSelection): make sure canvas is in charge of setting initial coords
  CHANGELOG.md
  src/canvas/SelectableCanvas.ts
  src/shapes/ActiveSelection.spec.ts
  src/shapes/ActiveSelection.ts
  src/shapes/__snapshots__/ActiveSelection.spec.ts.snap
Labels: fix-next

#9134 ci(e2e): node canvas visual tests
  CHANGELOG.md
  e2e/setup/index.ts
  e2e/setup/setupApp.ts
  e2e/setup/setupCoverage.ts
  e2e/setup/setupSelectors.ts
  e2e/tests/controls/polygon-controls/index.spec.ts
  e2e/tests/controls/rendering/index.spec.ts
  e2e/tests/selection/stale-state/index.spec.ts
  e2e/tests/template-with-node/common.ts
  e2e/tests/template-with-node/index.spec.ts
  e2e/tests/template-with-node/index.spec.ts-snapshots/textbox.png
  e2e/tests/template-with-node/index.ts
  e2e/tests/template/index.spec.ts
  e2e/tests/test.ts
  e2e/tests/text/adding-text/index.spec.ts
  e2e/tests/text/drag&drop/index.spec.ts
  e2e/tests/text/text-editing/index.spec.ts
  e2e/tsconfig.json
  e2e/utils/createNodeSnapshot.ts
Labels: CI/CD

#9197 fix(Textbox): implemente a fix for the style shifting issues on new lines
  CHANGELOG.md
  e2e/tests/text/adding-text/index.spec.ts
  e2e/tests/text/adding-text/index.spec.ts-snapshots/2-before-deleting-true.png
  e2e/tests/text/adding-text/index.spec.ts-snapshots/3-after-deleting-true.png
  e2e/tests/text/adding-text/index.spec.ts-snapshots/4-before-pasting-splitByGrapheme-true.png
  e2e/tests/text/adding-text/index.spec.ts-snapshots/5-after-pasting-splitByGrapheme-true.png
  src/shapes/Text/Text.ts
  src/shapes/Textbox.ts
Labels: bug, text

#9341 fix(IText): cursor width under group
  CHANGELOG.md
  src/shapes/IText/IText.test.ts
  src/shapes/IText/IText.ts
  src/shapes/IText/__snapshots__/IText.test.ts.snap
Labels: bug, text

#9329 fix(): Avoid firing twice in subselection
  CHANGELOG.md
  src/canvas/Canvas.ts
  src/canvas/__tests__/eventData.test.ts
Labels: group, selection

#9388 ci(e2e): fix babel compiling error
  CHANGELOG.md
  CONTRIBUTING.md
  playwright.setup.ts
Labels: CI/CD
