Repository fabricjs/fabric.js, pull requests merged in 2023-03, with the labels that each got.

#8677 chore(TS): types for `toObject` and additionaProperties
  CHANGELOG.md
  src/Shadow.ts
  src/controls/controlRendering.ts
  src/shapes/Circle.ts
  src/shapes/Object/FabricObject.ts
  src/shapes/Object/InteractiveObject.ts
  src/shapes/Object/Object.ts
  src/shapes/Object/ObjectGeometry.ts
  src/shapes/Object/ObjectOrigin.ts
  src/shapes/Object/ObjectProps.ts
  src/shapes/Object/types/BaseProps.ts
  src/shapes/Object/types/BorderProps.ts
  src/shapes/Object/types/ControlProps.ts
  src/shapes/Object/types/FabricObjectProps.ts
  src/shapes/Object/types/FillStrokeProps.ts
  src/shapes/Object/types/LockInteractionProps.ts
  src/shapes/Object/types/ObjectProps.ts
  src/shapes/Object/types/SerializedObjectProps.ts
  src/shapes/Object/types/index.ts
  src/typedefs.ts
Labels: types

#8755 ci(): remove unused imports on save
  .vscode/settings.json
Labels: CI/CD

#8759 ci(): disallow circular deps
  CHANGELOG.md
  rollup.config.mjs
Labels: CI/CD

#8135 ci(): codesandbox
  .codesandbox/README.md
  .codesandbox/ci.json
  .codesandbox/deploy.mjs
  .codesandbox/start.mjs
  .codesandbox/tasks.json
  .codesandbox/templates/next/.gitignore
  .codesandbox/templates/next/README.md
  .codesandbox/templates/next/REPRODUCE.md
  .codesandbox/templates/next/components/Canvas.tsx
  .codesandbox/templates/next/dev.mjs
  .codesandbox/templates/next/index.css
  .codesandbox/templates/next/next-env.d.ts
  .codesandbox/templates/next/next.config.mjs
  .codesandbox/templates/next/nodemon.config.json
  .codesandbox/templates/next/package.json
  .codesandbox/templates/next/pages/_app.tsx
  .codesandbox/templates/next/pages/_document.tsx
  .codesandbox/templates/next/pages/api/fabric.ts
  .codesandbox/templates/next/pages/index.tsx
  .codesandbox/templates/next/pages/node.tsx
  .codesandbox/templates/next/sandbox.config.json
  .codesandbox/templates/next/server.js
  .codesandbox/templates/next/tsconfig.json
  .codesandbox/templates/node/.gitignore
  .codesandbox/templates/node/README.md
  .codesandbox/templates/node/REPRODUCE.md
  .codesandbox/templates/node/nodemon.config.json
  .codesandbox/templates/node/package.json
  .codesandbox/templates/node/sandbox.config.json
  .codesandbox/templates/node/src/index.mjs
  .codesandbox/templates/vanilla/.gitignore
  .codesandbox/templates/vanilla/.parcelrc
  .codesandbox/templates/vanilla/README.md
  .codesandbox/templates/vanilla/REPRODUCE.md
  .codesandbox/templates/vanilla/index.html
  .codesandbox/templates/vanilla/package.json
  .codesandbox/templates/vanilla/sandbox.config.json
  .codesandbox/templates/vanilla/src/index.ts
  .codesandbox/templates/vanilla/src/styles.css
  .devcontainer/devcontainer.json
  .gitpod.yml
  .npmignore
  .prettierignore
  CHANGELOG.md
  CONTRIBUTING.md
  package-lock.json
  package.json
  scripts/index.mjs
  test/testem.config.js
Labels: CI/CD

#8711 fix(IText): layout regression
  CHANGELOG.md
  src/shapes/IText/ITextBehavior.ts
  src/shapes/Text/StyledText.ts
  src/shapes/Text/Text.ts
Labels: text

#8782 reflect NUM_FRACTION_DIGITS to SVG path data
  CHANGELOG.md
  src/shapes/Path.ts
  src/util/path.ts
  test/unit/path_utils.js
Labels: svg_output

#8803 ci(): reproduction templates + sandbox deploy
  .codesandbox/deploy.mjs
  .codesandbox/start.mjs
  .codesandbox/templates/next/README.md
  .codesandbox/templates/next/package.json
  .codesandbox/templates/node/README.md
  .codesandbox/templates/node/package.json
  .codesandbox/templates/vanilla/README.md
  .codesandbox/templates/vanilla/package.json
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/workflows/npmpublish.yml
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  package-lock.json
  package.json
  scripts/git.mjs
  scripts/index.mjs
Labels: CI/CD
