Repository fabricjs/fabric.js, pull requests merged in 2023-07, with the labels that each got.

#9039 ci(): install dev deps types
  CHANGELOG.md
  package-lock.json
  package.json
Labels: CI/CD

#9029 ci(): Refactor GHA for reuse and caching
  .github/actions/build-fabric-cached/action.yml
  .github/actions/cached-install/action.yml
  .github/workflows/build.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  jest.config.js
  package.json
Labels: CI/CD

#9082 fix(Text): `_getFontDeclaration`
  CHANGELOG.md
  src/shapes/Text/Text.ts
  test/unit/text.js
Labels: text

#9083 test(Text): Add some tests for text in Jest
  CHANGELOG.md
  jest.config.js
  rollup.config.mjs
  src/shapes/IText/IText.ts
  src/shapes/IText/ITextBehavior.test.ts
  src/shapes/IText/__snapshots__/ITextBehavior.test.ts.snap
  src/shapes/Text/Text.spec.ts
  src/shapes/Text/Text.ts
  src/shapes/Text/__snapshots__/Text.spec.ts.snap
  src/shapes/Textbox.spec.ts
  src/shapes/Textbox.ts
  src/shapes/__snapshots__/Textbox.spec.ts.snap
  test/unit/canvas_static.js
  test/unit/itext_key_behaviour.js
  test/unit/text.js
  test/unit/textbox.js
  test/visual/text.js
  test/visual/toDataURL.js
  toMatchRoundedSnapshot.ts
Labels: CI/CD

#9078 test(playwright): add snapshots, refactor utils, coverage
  .codesandbox/templates/vanilla/package.json
  .github/workflows/tests.yml
  .gitignore
  .npmignore
  CHANGELOG.md
  e2e/imports.ts
  e2e/setup/index.ts
  e2e/setup/setupApp.ts
  e2e/setup/setupCoverage.ts
  e2e/setup/setupSelectors.ts
  e2e/site/favicon.ico
  e2e/site/index.html
  e2e/tests/template/index.html
  e2e/tests/template/index.spec.ts
  e2e/tests/template/index.ts
  e2e/tests/test.ts
  e2e/tests/text/text-editing.spec.ts
  e2e/tests/text/text-editing/index.spec.ts
  e2e/tests/text/text-editing/index.spec.ts-snapshots/decrease-width-ml.png
  e2e/tests/text/text-editing/index.spec.ts-snapshots/decrease-width-mr.png
  e2e/tests/text/text-editing/index.spec.ts-snapshots/exit-editing.png
  e2e/tests/text/text-editing/index.spec.ts-snapshots/increase-width-ml.png
  e2e/tests/text/text-editing/index.spec.ts-snapshots/increase-width-mr.png
  e2e/tests/text/text-editing/index.spec.ts-snapshots/initial.png
  e2e/tests/text/text-editing/index.spec.ts-snapshots/start.png
  e2e/tests/text/text-editing/index.spec.ts-snapshots/typed.png
  e2e/tests/text/text-editing/index.ts
  e2e/tsconfig.json
  e2e/utils/CanvasUtil.ts
  e2e/utils/ObjectUtil.ts
  e2e/utils/executeInBrowser.ts
  e2e/utils/objects.ts
  package-lock.json
  package.json
  playwright.config.ts
  playwright.setup.ts
  tsconfig.json
Labels: CI/CD

#8374 fix(#8344): stroke projection
  CHANGELOG.md
  src/shapes/Polyline.ts
  src/util/index.ts
  src/util/internals/findRight.ts
  src/util/internals/index.ts
  src/util/misc/projectStroke/StrokeLineCapProjections.ts
  src/util/misc/projectStroke/StrokeLineJoinProjections.ts
  src/util/misc/projectStroke/StrokeProjectionsBase.ts
  src/util/misc/projectStroke/index.ts
  src/util/misc/projectStroke/types.ts
  src/util/misc/vectors.ts
  test/unit/polygon.js
  test/unit/util.js
  test/visual/stroke_projection.js
Labels: fix-next

#9108 ci(e2e): support relative imports
  .github/workflows/tests.yml
  CHANGELOG.md
  e2e/.babelrc.js
  e2e/imports.ts
  e2e/setup/setupApp.ts
  e2e/tests/template/index.ts
  e2e/tests/test.ts
  e2e/tests/text/text-editing/index.ts
  e2e/tsconfig.json
  package-lock.json
  package.json
  playwright.config.ts
  playwright.setup.ts
Labels: CI/CD

#9129 chore(TS): export types
  CHANGELOG.md
  fabric.ts
  src/filters/BlendColor.ts
  src/filters/Resize.ts
  src/filters/filters.ts
  src/shapes/Object/InteractiveObject.ts
  src/util/index.ts
  src/util/misc/matrix.ts
Labels: types
